const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),scoreEl=document.getElementById('score'),levelEl=document.getElementById('level'),linesEl=document.getElementById('lines');const W=10,H=20,S=30;const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]]];let grid,piece,score,lines,level,dropTimer,last=0,over=false;
function reset(){grid=Array.from({length:H},()=>Array(W).fill(0));score=0;lines=0;level=1;over=false;spawn();last=performance.now();cancelAnimationFrame(dropTimer);dropTimer=requestAnimationFrame(loop);update()}
function spawn(){const s=shapes[Math.floor(Math.random()*shapes.length)];piece={shape:s.map(r=>r.slice()),x:Math.floor((W-s[0].length)/2),y:0};if(collides(piece.shape,piece.x,piece.y))over=true}
function collides(shape,x,y){for(let r=0;r<shape.length;r++)for(let c=0;c<shape[r].length;c++)if(shape[r][c]&&(x+c<0||x+c>=W||y+r>=H||y+r>=0&&grid[y+r][x+c]))return true;return false}
function merge(){piece.shape.forEach((r,ri)=>r.forEach((v,ci)=>{if(v&&piece.y+ri>=0)grid[piece.y+ri][piece.x+ci]=1}))}
function clearLines(){let count=0;grid=grid.filter(r=>{if(r.every(Boolean)){count++;return false}return true});while(grid.length<H)grid.unshift(Array(W).fill(0));if(count){lines+=count;score+=[0,100,300,500,800][count]*level;level=Math.floor(lines/10)+1;update()}}
function move(dx){if(!over&&!collides(piece.shape,piece.x+dx,piece.y))piece.x+=dx}
function rotate(){if(over)return;const old=piece.shape,rot=old[0].map((_,i)=>old.map(row=>row[i]).reverse());if(!collides(rot,piece.x,piece.y))piece.shape=rot}
function drop(){if(over)return;if(!collides(piece.shape,piece.x,piece.y+1))piece.y++;else{merge();clearLines();spawn()}}
function hardDrop(){if(over)return;while(!collides(piece.shape,piece.x,piece.y+1))piece.y++;drop()}
function drawCell(x,y,active=false){ctx.fillStyle=active?'#65e7d0':'#33415e';ctx.fillRect(x*S+1,y*S+1,S-2,S-2);ctx.strokeStyle='#ffffff16';ctx.strokeRect(x*S+1,y*S+1,S-2,S-2)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#080d18';ctx.fillRect(0,0,canvas.width,canvas.height);grid.forEach((row,y)=>row.forEach((v,x)=>v&&drawCell(x,y)));if(piece&&!over)piece.shape.forEach((row,r)=>row.forEach((v,c)=>v&&piece.y+r>=0&&drawCell(piece.x+c,piece.y+r,true)));if(over){ctx.fillStyle='#080d18cc';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 26px system-ui';ctx.fillText('GAME OVER',canvas.width/2,canvas.height/2-10);ctx.font='13px system-ui';ctx.fillText('Ketuk 2× untuk mulai ulang',canvas.width/2,canvas.height/2+18)}}
function update(){scoreEl.textContent=score;levelEl.textContent=level;linesEl.textContent=lines}
function loop(now){if(now-last>Math.max(120,750-(level-1)*55)){drop();last=now}draw();dropTimer=requestAnimationFrame(loop)}
function act(a){if(a==='left')move(-1);if(a==='right')move(1);if(a==='rotate')rotate();if(a==='down')hardDrop();draw()}
document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')move(-1);else if(e.key==='ArrowRight')move(1);else if(e.key==='ArrowUp')rotate();else if(e.key==='ArrowDown')drop();else if(e.key===' ')hardDrop();draw()});reset();
