const canvas=document.getElementById('gameCanvas');const ctx=canvas.getContext('2d');const scoreEl=document.getElementById('score');const levelEl=document.getElementById('level');const linesEl=document.getElementById('lines');const W=10,H=20,S=30;const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]]];let grid=[],piece=null,score=0,lines=0,level=1,raf=0,last=0,over=false,touchX=0,touchY=0,touchMoved=false,lastTap=0;
function reset(){cancelAnimationFrame(raf);grid=Array.from({length:H},()=>Array(W).fill(0));score=0;lines=0;level=1;over=false;spawn();last=performance.now();update();draw();raf=requestAnimationFrame(loop)}
function spawn(){const s=shapes[Math.floor(Math.random()*shapes.length)];piece={shape:s.map(r=>r.slice()),x:Math.floor((W-s[0].length)/2),y:0};if(collides(piece.shape,piece.x,piece.y))over=true}
function collides(shape,x,y){for(let r=0;r<shape.length;r++)for(let c=0;c<shape[r].length;c++){if(!shape[r][c])continue;const gx=x+c,gy=y+r;if(gx<0||gx>=W||gy>=H)return true;if(gy>=0&&grid[gy][gx])return true}return false}
function merge(){piece.shape.forEach((row,r)=>row.forEach((v,c)=>{if(v&&piece.y+r>=0)grid[piece.y+r][piece.x+c]=1}))}
function clearLines(){let count=0;grid=grid.filter(row=>{if(row.every(Boolean)){count++;return false}return true});while(grid.length<H)grid.unshift(Array(W).fill(0));if(count){lines+=count;score+=([0,100,300,500,800][count]||800)*level;level=Math.floor(lines/10)+1;update()}}
function move(dx){if(!over&&!collides(piece.shape,piece.x+dx,piece.y)){piece.x+=dx;draw()}}
function rotate(){if(over)return;const old=piece.shape;const rot=old[0].map((_,i)=>old.map(row=>row[i]).reverse());let x=piece.x;if(collides(rot,x,piece.y)){if(!collides(rot,x-1,piece.y))x--;else if(!collides(rot,x+1,piece.y))x++;else return}piece.shape=rot;piece.x=x;draw()}
function drop(){if(over)return;if(!collides(piece.shape,piece.x,piece.y+1))piece.y++;else{merge();clearLines();spawn()}draw()}
function hardDrop(){if(over)return;while(!collides(piece.shape,piece.x,piece.y+1))piece.y++;drop()}
function update(){scoreEl.textContent=score;levelEl.textContent=level;linesEl.textContent=lines}
function drawCell(x,y,active){ctx.fillStyle=active?'#65e7d0':'#33415e';ctx.fillRect(x*S+1,y*S+1,S-2,S-2);ctx.strokeStyle='#ffffff16';ctx.strokeRect(x*S+1,y*S+1,S-2,S-2)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#080d18';ctx.fillRect(0,0,canvas.width,canvas.height);grid.forEach((row,y)=>row.forEach((v,x)=>{if(v)drawCell(x,y,false)}));if(piece&&!over)piece.shape.forEach((row,r)=>row.forEach((v,c)=>{if(v&&piece.y+r>=0)drawCell(piece.x+c,piece.y+r,true)}));if(over){ctx.fillStyle='#080d18cc';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 26px system-ui';ctx.fillText('GAME OVER',canvas.width/2,canvas.height/2-10);ctx.font='13px system-ui';ctx.fillText('Ketuk 2× untuk mulai ulang',canvas.width/2,canvas.height/2+18)}}
function loop(now){if(now-last>=Math.max(120,750-(level-1)*55)){drop();last=now}raf=requestAnimationFrame(loop)}
function act(action){if(action==='left')move(-1);else if(action==='right')move(1);else if(action==='rotate')rotate();else if(action==='down')hardDrop()}
document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')act('left');else if(e.key==='ArrowRight')act('right');else if(e.key==='ArrowUp')act('rotate');else if(e.key==='ArrowDown')drop();else if(e.key===' ')hardDrop()});
canvas.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchX=t.clientX;touchY=t.clientY;touchMoved=false},{passive:true});canvas.addEventListener('touchmove',e=>{e.preventDefault();const t=e.changedTouches[0],dx=t.clientX-touchX,dy=t.clientY-touchY;if(Math.abs(dx)>18||Math.abs(dy)>18)touchMoved=true},{passive:false});canvas.addEventListener('touchend',e=>{e.preventDefault();const t=e.changedTouches[0],dx=t.clientX-touchX,dy=t.clientY-touchY,now=Date.now();if(over&&Math.abs(dx)<35&&Math.abs(dy)<35){if(now-lastTap<450)reset();lastTap=now;return}if(Math.abs(dx)>35&&Math.abs(dx)>Math.abs(dy)){act(dx>0?'right':'left')}else if(dy>45){act('down')}else if(Math.abs(dx)<35&&Math.abs(dy)<35){if(now-lastTap>450)act('rotate');lastTap=now}},{passive:false});reset();